apiVersion: v1
kind: Pod
metadata:
  name: attacker-privileged
  namespace: runtime-lab
  labels:
    app: attacker-privileged
spec:
  restartPolicy: Never
  containers:
  - name: attacker
    image: alpine:3.20
    command: ["sleep", "9999"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-root
      mountPath: /host
      readOnly: true
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
