alertmanager:
  enabled: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    retention: 2d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
      limits:
        memory: 1200Mi
        cpu: 500m

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
